apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-git-tag
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Task to generate a build tag
  workspaces:
    - name: source
  results:
    - name: build-tag
      description: ID of the current build
  steps:
    - name: get-buildtag
      image: quay.io/michard/tekton_base_image:0.1.30
      script: |
        #!/bin/sh
        cd /workspace/source
        git config --global --add safe.directory /workspace/source
        git fetch --tags
        buildtag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "Current Build Tag:"
        echo ${buildtag} | tr -d "\n" | tee $(results.build-tag.path)